server:
  port: 8080
# MySQL??
spring:
  datasource:
    url: jdbc:mysql://172.28.200.14:3306/bin_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 5599399789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
    map-underscore-to-camel-case: true
#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.beans: DEBUG